### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by Jan21** [matthewsot/docs-vim#2]
Could this be used as an google docs add-on? I could not figure out how to install this. Thanks a lot.

**Comment by matthewsot** [comment]
Hi! Thanks for the interest. This is a Chrome add-on, Google Docs' add-on API does not allow this level of integration. But it's a Chrome add-on that affects the Google Docs editor.

I haven't done much work on it recently, but you should be able to load it into Chrome by: visiting chrome://extensions/ in Chrome -> check "developer mode" -> "load unpacked" and select the directory that you cloned this repo into. After that it should be enabled when you use Google Docs (unless Chrome's security model or some Docs editor IDs have changed since I last tested it).

If you get it working and have some favorite vim features that aren't implemented yet, feel free to try and add a few more features! Unfortunately it's not a very clean/modular codebase, but the majority of the important controlling code is in docs-vim.js, which is only 83 lines, so hopefully it's wade-throughable :) I have a list of my older GitHub projects that I want to fix up, but unfortunately just haven't been able to find the time for it.

**Comment by Jan21** [comment]
Thanks a lot for the description! I was already trying this and it did not work. I found that I had to download docs-plus folder separately because it was empty. It was probably because I did not git clone the repository but downloaded it as zip.

**Comment by matthewsot** [comment]
Awesome, glad it's working!

**Comment by vic-cw** [comment]
I think it would be very helpful to add these instructions into the README
