### ISSUE TITLE
Support for 'a' key.

### ISSUE THREAD

**Issue by antoj2** [matthewsot/docs-vim#8]
Hey just wondering, can you add support for the 'a' key so you can insert after the cursor?

**Comment by matthewsot** [comment]
Hello!

Yes, it should be possible. I would suggest looking at the implementation of the 'i' key, and then just copy it for the 'a' key except also add a right-arrow click (check out implementation of the 'n' key for how to do that).

If you get something working, feel free to send a PR!

Also, while I greatly appreciate the input + work you did in the other PR, I do want to make sure you know about the newly-added [update section on the README](https://github.com/matthewsot/docs-vim#update) --- basically, docs-vim will probably stop working for good because of major changes on the Google side in the next few months. So you may want to consider that when deciding how much effort to put into fixing either of those issues.

Thanks again!

**Comment by matthewsot** [comment]
Closed with merge of #9, thanks to @r2dev2
